#---------------------------------
# development mode => local環境
#---------------------------------
development:
  adapter: mysql2
  encoding: utf8
  database: pochivel
  pool: 5
  username: pochivel
  password: pochivel
  collation: utf8_general_ci
  host: 127.0.0.1
  port: 3306

#---------------------------------
# staging mode
#---------------------------------
staging:
  adapter: mysql2
  encoding: utf8
  database: pochivel
  pool: 5
  username: pochivel
  password: pochivel
  collation: utf8_general_ci
  host: 127.0.0.1
  port: 3306

#---------------------------------
# production mode
#---------------------------------
production:
  adapter: mysql2
  encoding: utf8
  database: pochivel
  pool: 5
  username: pochivel
  password: pochivel
  collation: utf8_general_ci
  host: 127.0.0.1
  port: 3306